import {io} from 'socket.io-client';
import {World} from './world';
import {TRACK,N,COLORS} from '../shared/track';
import type {Snapshot,Reply,Input} from '../shared/types';
import './style.css';
const ui=document.querySelector<HTMLElement>('#ui')!,game=document.querySelector<HTMLElement>('#game')!,connection=document.querySelector<HTMLElement>('#connection')!,toastEl=document.querySelector<HTMLElement>('#toast')!;
const base=import.meta.env.BASE_URL,server=import.meta.env.VITE_GAME_SERVER_URL||'http://localhost:3001';
const namespace=`parcel-panic:v1:${base}:${server}`;
const storage={get(key:string){try{return sessionStorage.getItem(namespace+key);}catch{return null;}},set(key:string,value:string){try{sessionStorage.setItem(namespace+key,value);}catch{}},remove(key:string){try{sessionStorage.removeItem(namespace+key);}catch{}}};
let saved:{code:string;id:string;token:string;name:string}|null=null;try{saved=JSON.parse(storage.get(':session')||'null');}catch{}
let state:Snapshot|null=null,myId=saved?.id||'',screenKey='',lastState=0,connected=false,joining=false,error='',toastTimer=0,seq=0,sound=false,audio:AudioContext|null=null,engine:OscillatorNode|null=null,engineGain:GainNode|null=null,focused=true;
const keys=new Set<string>();let oneShotUse=false,oneShotRespawn=false;let world:World;
try{world=new World(game);}catch{ui.innerHTML='<section class="fatal"><h1>We need a little graphics power.</h1><p>WebGL could not start. Enable hardware acceleration and reload this page in a current desktop browser.</p></section>';throw new Error('WebGL unavailable');}
const socket=io(server,{autoConnect:false,reconnection:true,reconnectionDelay:500,reconnectionDelayMax:2500,timeout:7000,transports:['websocket','polling']});
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const hex=(c:number)=>'#'+c.toString(16).padStart(6,'0');
const time=(s:number)=>`${Math.floor(s/60)}:${(s%60).toFixed(2).padStart(5,'0')}`;
const ordinal=(n:number)=>`${n}${n===1?'st':n===2?'nd':n===3?'rd':'th'}`;
function toast(message:string){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>toastEl.classList.remove('show'),3500);}
function beep(frequency=440,duration=.12){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function enableAudio(){if(!audio){audio=new AudioContext();engine=audio.createOscillator();engine.type='triangle';engineGain=audio.createGain();engineGain.gain.value=0;engine.connect(engineGain).connect(audio.destination);engine.start();}void audio.resume();}
function focusGame(clear=true){game.focus({preventScroll:true});if(clear)keys.clear();focused=true;enableAudio();}
function controls(){return `<div class="controls"><span><kbd>W</kbd><kbd>↑</kbd> Accelerate</span><span><kbd>S</kbd><kbd>↓</kbd> Brake / reverse</span><span><kbd>A</kbd><kbd>D</kbd> Steer</span><span><kbd>Shift</kbd> Drift → release to boost</span><span><kbd>Space</kbd> Use parcel</span><span><kbd>R</kbd> Rescue</span></div>`;}
function brand(){return `<div class="brand"><span class="brand-mark" aria-hidden="true">P<span>↗</span></span><span>PARCEL<br>PANIC</span></div>`;}
function render(){
 const phase=state?.phase||'home';if(phase!=='racing'&&engineGain&&audio)engineGain.gain.setTargetAtTime(0,audio.currentTime,.1);const roster=state?.players.map(p=>`${p.id}:${p.connected}:${p.active}:${p.finish}:${p.dnf}`).join('|')||'';
 const inRace=phase==='racing'||phase==='countdown';const key=[phase,inRace?'':roster,inRace?'':state?.host,myId,error,joining].join(';');if(key===screenKey)return;screenKey=key;
 const mine=state?.players.find(p=>p.id===myId),host=state?.host===myId;
 if(!state){const urlCode=new URL(location.href).searchParams.get('room')||'';
 ui.innerHTML=`<section class="entry"><header>${brand()}<span class="edition">Island express<br>2–8 friends online</span></header><div class="intro"><div class="stamp">SPECIAL DELIVERY!</div><h1>Small karts.<br>Big rush.</h1><p>Clock out. Floor it. Race your friends through the island depot, over the flyover, and straight into a little friendly chaos.</p></div><form id="entry-form"><label for="name">Your driver name</label><input id="name" name="name" maxlength="18" autocomplete="nickname" placeholder="e.g. Speedy Sam" value="${esc(saved?.name||storage.get(':name')||'')}" required><div class="actions"><button id="create" type="button" class="primary" ${joining?'disabled':''}>${joining?'Connecting…':'Create a room'} <span>↗</span></button><span class="or">or join your crew</span><div class="join-row"><input id="code" aria-label="Room code" placeholder="ROOM CODE" maxlength="5" value="${esc(urlCode.toUpperCase())}" autocapitalize="characters"><button id="join" type="submit" ${joining?'disabled':''}>Join →</button></div></div><p class="error" role="alert">${esc(error)}</p></form><details><summary>How to drive</summary>${controls()}<p>Collect a parcel: <b>Turbo</b> gives a speed boost. <b>Air horn</b> slows rivals within 18m on your road level. Charge a drift until the meter turns gold, then release Shift.</p></details><footer>3 laps · one island · questionable delivery times</footer></section><div class="world-caption"><b>POSTCARD CIRCUIT</b><span>Mind the air mail gap.</span><span class="route-line">↗ AIR MAIL &nbsp; ⤴ FLYOVER &nbsp; ⚑ DISPATCH</span></div>`;
 document.querySelector('#entry-form')!.addEventListener('submit',e=>{e.preventDefault();void enter(false);});document.querySelector('#create')!.addEventListener('click',()=>void enter(true));
 }else if(phase==='lobby'||phase==='results'){
 const results=phase==='results',players=[...state.players].sort((a,b)=>results?(a.active?0:1)-(b.active?0:1)||a.place-b.place:0),count=players.filter(p=>p.connected).length;
 ui.innerHTML=`<section class="room-panel"><header>${brand()}<button class="quiet" id="leave">Leave room</button></header><div class="room-heading"><span class="stamp">${results?'DELIVERY COMPLETE':'YOUR CREW'}</span><h1>${results?'That’s a wrap.':'Ready to roll?'}</h1><p>${results?'The parcels can wait. Fancy another round?':'Share the room code or send a link to your friends.'}</p></div><div class="room-ticket"><div><small>Room code</small><strong id="room-code">${state.code}</strong></div><button id="share">Copy invite ↗</button></div><ol class="roster">${players.map(p=>`<li><span class="driver-swatch" style="--kart:${hex(p.color)}">${results&&p.active?p.place:'●'}</span><span class="driver-name">${esc(p.name)} ${p.id===myId?'<small>you</small>':''}<small>${!p.connected?'Reconnecting…':p.id===state!.host?'Host':results&&!p.active?'Racing next round':'Ready'}</small></span>${results&&p.active?`<b class="finish-time">${p.finish!==null?time(p.finish):'DNF'}</b>`:'<span class="ready-dot" aria-label="'+(p.connected?'Connected':'Disconnected')+'">'+(p.connected?'✓':'…')+'</span>'}</li>`).join('')}</ol><button id="start" class="primary full" ${!host||count<2?'disabled':''}>${host?count<2?'Waiting for a friend…':results?'Race again ↗':`Start race · ${count} drivers ↗`:'Waiting for the host…'}</button><p class="room-note">${host?'You’re the host. Start when your crew is ready.':'The host starts the race for everyone.'} ${count}/8 connected.</p><details><summary>Controls & parcel power</summary>${controls()}<p>Gold drift meter = boost ready. Turbo: 3 seconds of extra speed. Air horn: slows nearby rivals on your level. R puts you back at your last checkpoint.</p></details></section><div class="world-caption"><b>${results?'NEXT DISPATCH?':'POSTCARD CIRCUIT'}</b><span>${results?'Same friends. Another chance.':'Air mail jump. Two-level flyover. Three laps.'}</span></div>`;
 document.querySelector('#leave')!.addEventListener('click',leave);document.querySelector('#share')!.addEventListener('click',share);document.querySelector('#start')!.addEventListener('click',()=>{enableAudio();socket.timeout(5000).emit('start',{},(err:Error|null,r:Reply)=>{if(err||!r.ok)toast(r?.error||'Could not reach the server. Try again.');});});
 }else{
 ui.innerHTML=`<div class="race-top"><div class="position"><strong id="place">1<span>st</span></strong><span id="field-size">of ${state.players.filter(p=>p.active).length}</span></div><div class="lap-ticket"><small>LAP</small><b id="lap">1 <span>/ 3</span></b><span id="race-time">0:00.00</span></div><div class="race-menu"><button id="sound" aria-label="Toggle sound">${sound?'Sound on':'Sound off'}</button><button id="help">Controls</button><button id="leave">Leave</button></div></div><ol id="live-order" class="live-order"></ol><div id="center-message" class="center-message"></div><div id="help-panel" class="help-panel" hidden><h2>Make every delivery count.</h2>${controls()}<p>Hold Shift while turning. When the drift meter turns gold, release for a boost. R rescues you to your last checkpoint. Click the track to focus keyboard controls.</p><button id="close-help">Let’s drive →</button></div><div class="race-bottom"><div class="minimap-wrap"><canvas id="minimap" width="240" height="184" aria-label="Track map with racers"></canvas><span>POSTCARD CIRCUIT</span></div><div class="drive-info"><div class="speed"><b id="speed">0</b><span>km/h</span></div><div class="drift-label"><span id="drift-text">HOLD SHIFT + TURN TO DRIFT</span><div class="drift-meter"><i id="drift-fill"></i></div></div></div><button id="item" class="item-slot"><span class="item-icon" id="item-icon">□</span><span><b id="item-name">Find a parcel</b><small id="item-hint">Collect a yellow box</small></span><kbd>Space</kbd></button></div><div class="focus-tip" id="focus-tip" hidden>Click the track to resume keyboard control</div>`;
 document.querySelector('#sound')!.addEventListener('click',()=>{enableAudio();sound=!sound;document.querySelector('#sound')!.textContent=sound?'Sound on':'Sound off';beep();focusGame();});
 document.querySelector('#help')!.addEventListener('click',()=>{keys.clear();document.querySelector<HTMLElement>('#help-panel')!.hidden=false;});document.querySelector('#close-help')!.addEventListener('click',()=>{document.querySelector<HTMLElement>('#help-panel')!.hidden=true;focusGame();});document.querySelector('#leave')!.addEventListener('click',leave);document.querySelector('#item')!.addEventListener('click',()=>{oneShotUse=true;focusGame();});
 focusGame(false);updateHUD();
 }
}
async function enter(create:boolean){const name=document.querySelector<HTMLInputElement>('#name')!.value.trim(),code=document.querySelector<HTMLInputElement>('#code')!.value.trim().toUpperCase();if(!name){error='Give your driver a name first.';render();document.querySelector<HTMLInputElement>('#name')?.focus();return;}if(!create&&!/^[A-Z2-9]{5}$/.test(code)){error='Enter the five-character room code.';storage.set(':name',name);render();return;}
 enableAudio();storage.set(':name',name);joining=true;error='';render();if(!socket.connected){joining=false;error='The game server is not connected yet. Check the connection banner and try again.';render();return;}
 socket.timeout(7000).emit('enter',{name,code,create},(err:Error|null,r:Reply)=>{joining=false;if(err||!r.ok){error=r?.error||'The server did not reply. Try again.';render();return;}saveSession(r,name);beep(600);});}
function saveSession(r:Reply,name:string){myId=r.id!;saved={id:r.id!,token:r.token!,code:r.code!,name};storage.set(':session',JSON.stringify(saved));const url=new URL(location.href);url.searchParams.set('room',r.code!);history.replaceState(null,'',url);screenKey='';render();}
function leave(){socket.emit('leave');state=null;world.current=null;saved=null;myId='';keys.clear();storage.remove(':session');const url=new URL(location.href);url.searchParams.delete('room');history.replaceState(null,'',url);screenKey='';error='';render();}
async function share(){if(!state)return;const url=new URL(location.href);url.searchParams.set('room',state.code);url.hash='';try{await navigator.clipboard.writeText(url.href);toast('Invite copied. Send it to your crew.');}catch{toast(`Room code: ${state.code}. Copy the address bar to share a link.`);}}
socket.on('connect',()=>{connected=true;connection.classList.remove('warning');if(saved){socket.timeout(7000).emit('enter',{name:saved.name,code:saved.code,token:saved.token},(err:Error|null,r:Reply)=>{if(err){toast('Rejoin timed out. Reconnecting…');socket.disconnect().connect();return;}if(!r.ok){state=null;world.current=null;myId='';saved=null;storage.remove(':session');error=r.error||'The room ended. Create a new room.';render();}else{saveSession(r,saved!.name);toast('Back with your crew.');}});}render();});
socket.on('disconnect',()=>{connected=false;keys.clear();updateConnection();});socket.on('connect_error',()=>{connected=false;updateConnection();});socket.on('serverClosing',()=>{toast('The server is restarting. Reconnecting…');});socket.on('replaced',()=>{saved=null;storage.remove(':session');state=null;world.current=null;myId='';error='This driver connected in another tab. Create or join with a new driver.';render();});
let lastLap=0,lastItem='',lastRace=0,lastRespawns=0,lastCount='';
socket.on('state',(s:Snapshot)=>{
 if(!saved||s.code!==saved.code)return;state=s;lastState=performance.now();world.update(s,myId);
 const me=s.players.find(p=>p.id===myId);if(s.raceId!==lastRace){lastRace=s.raceId;lastLap=0;lastRespawns=0;keys.clear();}
 if(me){if(me.lap>lastLap){beep(880,.3);toast(me.lap===3?'Signed, sealed, delivered!':`Lap ${me.lap+1} — keep it moving!`);}if(me.item&&me.item!==lastItem){beep(660);toast(me.item==='turbo'?'Turbo parcel! Space for a speed boost.':'Air horn! Space to slow nearby rivals.');}if(me.respawns>lastRespawns)toast('Back on route. Your earned checkpoints are safe.');lastLap=me.lap;lastItem=me.item||'';lastRespawns=me.respawns;}
 render();updateHUD();updateConnection();
});
function updateConnection(){const stale=state&&performance.now()-lastState>2500;connection.textContent=!connected?(state||saved?'Connection lost — retrying… Your race spot is held for 90 seconds.':'Connecting to the game server… If this persists, check the backend URL and allowed origin.'):stale?'Waiting for race updates — controls paused until the server responds.':'';connection.classList.toggle('warning',!connected||!!stale);if((!connected||stale)&&engineGain&&audio)engineGain.gain.setTargetAtTime(0,audio.currentTime,.1);}
function updateHUD(){if(!state||!['racing','countdown'].includes(state.phase))return;const me=state.players.find(p=>p.id===myId);if(!me)return;const active=state.players.filter(p=>p.active).sort((a,b)=>a.place-b.place);
 const set=(id:string,text:string)=>{const e=document.getElementById(id);if(e)e.textContent=text;};
 set('place',me.active?ordinal(me.place):'—');set('lap',me.active?`${Math.min(me.lap+1,3)} / 3`:'WAIT');set('race-time',time(Math.max(0,state.serverTime-state.startAt)));set('speed',String(Math.round(Math.abs(me.speed)*3.6)));set('item-name',me.item==='turbo'?'Turbo':me.item==='pulse'?'Air horn':'Find a parcel');set('item-icon',me.item==='turbo'?'↯':me.item==='pulse'?'◉':'□');set('item-hint',me.item==='turbo'?'3-second speed boost':me.item==='pulse'?'Slow rivals within 18m':'Collect a yellow box');
 const slot=document.querySelector<HTMLButtonElement>('#item');if(slot)slot.disabled=!me.active||me.finish!==null||me.dnf;slot?.classList.toggle('loaded',!!me.item);const fill=document.getElementById('drift-fill');if(fill){fill.style.width=`${Math.min(1,me.driftCharge/1.5)*100}%`;fill.classList.toggle('charged',me.driftCharge>.65);}set('drift-text',me.boost>0?'EXPRESS DELIVERY!':me.driftCharge>.65?'BOOST READY · RELEASE SHIFT':me.drifting?'CHARGING DRIFT…':'HOLD SHIFT + TURN TO DRIFT');
 const order=document.getElementById('live-order');if(order)order.innerHTML=active.map(p=>`<li class="${p.id===myId?'is-me':''}"><b>${p.place}</b><i style="background:${hex(p.color)}"></i><span>${esc(p.name)}</span><small>${p.finish!==null?'⚑':p.dnf?'DNF':!p.connected?'…':`L${Math.min(3,p.lap+1)}`}</small></li>`).join('');
 const center=document.getElementById('center-message')!;
 if(!me.active){center.innerHTML='<strong>Next dispatch</strong><span>You joined during a race. Watch the island; you’ll race in the next round.</span>';}
 else if(state.phase==='countdown'){const count=String(Math.max(1,Math.ceil(state.startAt-state.serverTime)));center.innerHTML=`<strong class="count">${count}</strong><span>GET READY · HOLD W TO GO</span>`;if(lastCount!==count){beep(300+Number(count)*80);lastCount=count;}}
 else if(me.finish!==null||me.dnf){center.innerHTML=`<strong>${me.finish!==null?`${ordinal(me.place)} · Delivered!`:'Dispatch ended'}</strong><span>${me.finish!==null?time(me.finish)+' · ':''}Waiting for the crew${state.endAt?` · ${Math.max(0,Math.ceil(state.endAt-state.serverTime))}s`:''}</span>`;}
 else if(state.serverTime-state.startAt<1.2){center.innerHTML='<strong class="count go">GO!</strong>';}
 else{center.innerHTML='';if(me.stun>0)center.innerHTML='<span class="hit">AIR HORN! Speed reduced</span>';else{const p=TRACK[Math.floor(me.segment)%N]!;if(me.speed>4&&Math.sin(me.heading)*p.tx+Math.cos(me.heading)*p.tz<-.25)center.innerHTML='<span class="hit">WRONG WAY · Follow the yellow arrows</span>';}}
 drawMap(active);const tip=document.querySelector<HTMLElement>('#focus-tip');if(tip)tip.hidden=focused;
 if(engine&&engineGain&&audio){engine.frequency.setTargetAtTime(50+Math.abs(me.speed)*4,audio.currentTime,.1);engineGain.gain.setTargetAtTime(sound&&focused&&state.phase==='racing'&&me.finish===null?.018:0,audio.currentTime,.12);}
}
function drawMap(players:Snapshot['players']){const canvas=document.querySelector<HTMLCanvasElement>('#minimap');if(!canvas)return;const c=canvas.getContext('2d')!;c.clearRect(0,0,240,184);const point=(x:number,z:number)=>[120+x*1.03,92+z*1.03];c.lineWidth=8;c.strokeStyle='#7e999c';c.beginPath();TRACK.forEach((p,i)=>{const[x,y]=point(p.x,p.z);if(i===0)c.moveTo(x!,y!);else c.lineTo(x!,y!);});c.closePath();c.stroke();c.lineWidth=2;c.strokeStyle='#dce8e3';c.stroke();c.fillStyle='#ffffff';c.fillRect(114,87,12,5);for(const p of [...players].reverse()){const[x,y]=point(p.x,p.z);c.beginPath();c.arc(x!,y!,p.id===myId?5.5:4,0,Math.PI*2);c.fillStyle=hex(p.color);c.fill();c.lineWidth=p.id===myId?2:1;c.strokeStyle='#fff';c.stroke();}}
const relevant=new Set(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight','Space','KeyR']);
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLElement&&e.target.matches('input,textarea,button,summary'))return;if(relevant.has(e.code)&&state&&['racing','countdown'].includes(state.phase)){e.preventDefault();focused=true;if(!e.repeat){if(e.code==='Space')oneShotUse=true;if(e.code==='KeyR')oneShotRespawn=true;}keys.add(e.code);}});
window.addEventListener('keyup',e=>{keys.delete(e.code);});window.addEventListener('blur',()=>{keys.clear();focused=false;});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();focused=false;}});game.addEventListener('pointerdown',()=>focusGame());
setInterval(()=>{updateConnection();if(!state||!connected||performance.now()-lastState>2500)return;const input:Input={throttle:(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),steer:(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),drift:keys.has('ShiftLeft')||keys.has('ShiftRight'),use:oneShotUse,respawn:oneShotRespawn,seq:seq++};socket.volatile.emit('input',input);oneShotUse=false;oneShotRespawn=false;},1000/30);
// Read-only telemetry for diagnostics and repeatable browser verification. No server state or inputs can be mutated here.
Object.defineProperty(window,'parcelDiagnostics',{value:()=>JSON.parse(JSON.stringify({state,myId,connected,base,server,frame:world.renderer.info.render})),writable:false});
render();socket.connect();
