import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const checks=[],errors=[],children=[],contexts=[];let browser,backend,preview;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const url='http://localhost:4174/games/a/';
const env={...process.env,PORT:'3101',HOST:'127.0.0.1',ALLOWED_ORIGINS:'http://localhost:4174',BASE_PATH:'/games/a/',PREVIEW_PORT:'4174'};
function launch(cmd,args){const p=spawn(cmd,args,{env,stdio:['ignore','pipe','pipe']});children.push(p);p.stdout.on('data',()=>{});p.stderr.on('data',d=>console.log(String(d)));return p;}
async function waitHttp(url){for(let i=0;i<80;i++){try{if((await fetch(url)).ok)return;}catch{}await pause(100);}throw new Error('Not ready: '+url);}
async function page(){const c=await browser.newContext({viewport:{width:1000,height:720}});contexts.push(c);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForFunction(()=>window.parcelDiagnostics?.().connected);return p;}
async function enter(p,name,code){await p.locator('#name').fill(name);if(code){await p.locator('#code').fill(code);await p.locator('#join').click({force:true});}else await p.locator('#create').click({force:true});await p.locator('#room-code').waitFor();return p.locator('#room-code').innerText();}
const diag=p=>p.evaluate(()=>window.parcelDiagnostics());
const embed=createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(`<html><head><title>Embedding boundary test</title></head><body style="margin:0"><iframe title="Parcel Panic" src="${url}" allow="autoplay; fullscreen" style="width:100vw;height:95vh;border:0"></iframe></body></html>`);});
try{
 backend=launch(process.execPath,['dist/server/server/index.js']);preview=launch(process.execPath,['node_modules/vite/bin/vite.js','preview']);await waitHttp('http://localhost:3101/health');await waitHttp(url);
 console.log('Checkpoint',checks.length+1);checks.push('Built backend honors PORT=3101/HOST and answers /health');
 browser=await chromium.launch({headless:false,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});
 const first=await page();const requests=[];first.on('request',r=>requests.push(r.url()));await first.reload();await first.waitForFunction(()=>window.parcelDiagnostics?.().connected);await first.screenshot({path:'artifacts/nested-home.png'});const code=await enter(first,'Nested host');assert(first.url().includes('/games/a/?room='));assert.equal((await diag(first)).base,'/games/a/');
 console.log('Checkpoint',checks.length+1);checks.push('Production static client rendered at /games/a/ and room URL retained prefix');
 const peers=[first];for(let i=1;i<8;i++){const p=await page();await enter(p,'Browser '+i,code);peers.push(p);}for(const p of peers)await p.waitForFunction(()=>window.parcelDiagnostics().state?.players.length===8);
 await first.screenshot({path:'artifacts/eight-browser-lobby.png'});console.log('Checkpoint',checks.length+1);checks.push('Eight real Chromium browser contexts displayed the same eight-driver lobby');
 const ninth=await page();await ninth.locator('#name').fill('Ninth browser');await ninth.locator('#code').fill(code);await ninth.locator('#join').click({force:true});await ninth.getByText('This room is full (8 drivers).').waitFor();console.log('Checkpoint',checks.length+1);checks.push('Ninth real browser saw the room-full message');
 const separate=await page();const separateCode=await enter(separate,'Separate room');assert.notEqual(separateCode,code);await first.locator('#start').click({force:true});for(const p of peers)await p.waitForFunction(()=>window.parcelDiagnostics().state?.phase==='racing');assert.equal((await diag(separate)).state.phase,'lobby');console.log('Checkpoint',checks.length+1);checks.push('Eight real browsers entered one synchronized race; separate browser room stayed in its own lobby');
 // Actual key presses drive the built game, rather than a telemetry/input shortcut.
 await first.locator('#game').focus();await first.keyboard.down('w');await pause(1800);await first.keyboard.up('w');const moved=(await diag(first)).state.players.find(p=>p.name==='Nested host');assert(moved.speed>10);assert(moved.segment>8);await first.screenshot({path:'artifacts/eight-browser-race.png'});console.log('Checkpoint',checks.length+1);checks.push('Built client keyboard acceleration changed authoritative position visible to all peers');
 const before=await diag(peers[2]);await peers[2].context().setOffline(true);await peers[2].locator('#connection.warning').waitFor({timeout:20000});await peers[2].screenshot({path:'artifacts/disconnected.png'});await pause(1200);await peers[2].context().setOffline(false);await peers[2].waitForFunction(id=>{const d=window.parcelDiagnostics();return d.connected&&d.state?.players.find(p=>p.id===id)?.connected;},before.myId,{timeout:20000});assert.equal((await diag(peers[2])).myId,before.myId);console.log('Checkpoint',checks.length+1);checks.push('Real browser offline/online cycle displayed warning and restored the same ongoing racer');
 // Free renderer resources before iframe verification.
 for(const p of peers.slice(1))await p.context().close();await ninth.context().close();
 await new Promise(r=>embed.listen(4180,'127.0.0.1',r));const embedContext=await browser.newContext({viewport:{width:1200,height:820}});contexts.push(embedContext);const parent=await embedContext.newPage();await parent.goto('http://localhost:4180/');const frame=parent.frames().find(f=>f.url().startsWith(url));assert(frame);await frame.waitForFunction(()=>window.parcelDiagnostics?.().connected);await frame.locator('#name').fill('Frame driver');await frame.locator('#create').click({force:true});await frame.locator('#room-code').waitFor();const frameCode=await frame.locator('#room-code').innerText();const buddy=await page();await enter(buddy,'Frame friend',frameCode);await frame.locator('#start').click({force:true});await frame.waitForFunction(()=>window.parcelDiagnostics().state?.phase==='racing');await frame.locator('#sound').click({force:true});await frame.locator('#game').focus();await parent.keyboard.down('w');await pause(1400);await parent.keyboard.up('w');const fd=await frame.evaluate(()=>window.parcelDiagnostics());assert(fd.state.players.find(p=>p.id===fd.myId).speed>5);assert.equal(await frame.locator('#sound').innerText(),'Sound on');await parent.screenshot({path:'artifacts/iframe-race.png'});console.log('Checkpoint',checks.length+1);checks.push('Cross-origin iframe: lobby, start, keyboard focus/driving, sound activation control and nested assets worked');
 // Backend restart must lose rooms honestly and recover to a usable entry screen.
 backend.kill('SIGTERM');await new Promise(r=>backend.once('exit',r));await first.locator('#connection.warning').waitFor({timeout:10000});backend=launch(process.execPath,['dist/server/server/index.js']);await waitHttp('http://localhost:3101/health');await first.getByText(/Room no longer exists/).waitFor({timeout:20000});const fresh=await enter(first,'Fresh dispatch');assert(fresh);console.log('Checkpoint',checks.length+1);checks.push('Actual backend restart explained lost rooms; browser successfully created a fresh room');
 const assets=requests.filter(x=>x.includes('/assets/'));assert(assets.length>=2);assert(assets.every(x=>x.startsWith(url+'assets/')));console.log('Checkpoint',checks.length+1);checks.push('All observed static JS/CSS asset URLs stayed beneath the configured nested base');
 assert.equal(errors.length,0);console.log('PASS',JSON.stringify(checks));
}catch(e){console.error(e);console.log('Checkpoint',checks.length+1);checks.push('FAILED: '+e.stack);process.exitCode=1;}
finally{if(browser)await browser.close();for(const p of children)p.kill('SIGTERM');embed.close();await writeFile('artifacts/deployment-report.json',JSON.stringify({checks,errors,url,date:new Date().toISOString()},null,2));}
